# This is a sample deployment manifest file for a simple web application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-github-actions
  namespace: frontend
  labels:
    app: react-app-github-actions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app-github-actions
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: react-app-github-actions
    spec:
      containers:
      - name: react-app-github-actions
        image: boubamahir/react-app-github-actions:10361358339
        # image: boubamahir/react-app-github-actions:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000